---
sidebar: sidebar 
permalink: genai-engine-instance.html 
keywords: genai engine, instance, ec2, role, iam role, permissions, security group, inbound, outbound, private endpoints 
summary: 'Lorsque vous déployez l"infrastructure GenAI, la fabrique de workloads crée une instance EC2 pour le moteur GenAI. Il crée également un rôle IAM, un groupe de sécurité et des terminaux privés pour cette instance. Vous souhaitez en savoir plus sur les composants créés par l"usine de workloads dans votre environnement AWS.' 
---
= Composants du moteur NetApp GenAI
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Lorsque vous déployez l'infrastructure GenAI, la fabrique de workloads crée une instance EC2 pour le moteur GenAI. Il crée également un rôle IAM, un groupe de sécurité et des terminaux privés pour cette instance. Vous souhaitez en savoir plus sur les composants créés par l'usine de workloads dans votre environnement AWS.

Type d'instance EC2:: m5.large
Rôle IAM:: L'instance du moteur GenAI a besoin d'autorisations pour envoyer des segments de données au modèle d'intégration sur Amazon Bedrock et pour communiquer avec le système interne du service NetApp ai. Le rôle IAM comprend les autorisations suivantes :
+
--
.Autorisations de rôle IAM
[%collapsible]
====
[source, json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ssm:DescribeDocument",
        "ssm:DescribeAssociation",
        "ssm:GetDeployablePatchSnapshotForInstance",
        "ssm:GetManifest",
        "ssm:ListInstanceAssociations",
        "ssm:ListAssociations",
        "ssm:PutInventory",
        "ssm:PutComplianceItems",
        "ssm:PutConfigurePackageResult",
        "ssm:UpdateAssociationStatus",
        "ssm:UpdateInstanceAssociationStatus",
        "ssm:UpdateInstanceInformation",
        "ssmmessages:CreateControlChannel",
        "ssmmessages:CreateDataChannel",
        "ssmmessages:OpenControlChannel",
        "ssmmessages:OpenDataChannel"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "ssm:GetParameter"
      ],
      "Resource": "arn:aws:ssm:*:*:parameter/netapp/wlmai/*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "fsx:DescribeVolumes",
        "fsx:DescribeStorageVirtualMachines",
        "fsx:DescribeFileSystems"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "fsx:TagResource",
        "fsx:ListTagsForResource"
      ],
      "Resource": [
        "arn:aws:fsx:*:*:storage-virtual-machine/*/*",
        "arn:aws:fsx:*:*:volume/*/*"
      ],
      "Effect": "Allow"
    },
    {
      "Action": [
        "fsx:CreateVolume"
      ],
      "Resource": [
        "arn:aws:fsx:*:*:volume/*/*",
        "arn:aws:fsx:*:*:storage-virtual-machine/*/*"
      ],
      "Effect": "Allow"
    },
    {
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/netapp:wlmai:c92e9ed6-dcbb-45f7-95f0-58647ebec9d7:kbId": "*"
        }
      },
      "Action": "fsx:DeleteVolume",
      "Resource": [
        "arn:aws:fsx:*:*:volume/*/*",
        "arn:aws:fsx:*:*:backup/*"
      ],
      "Effect": "Allow"
    },
    {
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/netapp:wlmai:c92e9ed6-dcbb-45f7-95f0-58647ebec9d7": "*"
        }
      },
      "Action": "fsx:UntagResource",
      "Resource": "arn:aws:fsx:*:*:storage-virtual-machine/*/*",
      "Effect": "Allow"
    },
    {
      "Condition": {
        "StringLike": {
          "aws:ResourceTag/netapp:wlmai:c92e9ed6-dcbb-45f7-95f0-58647ebec9d7:kbId": "*"
        }
      },
      "Action": "fsx:UntagResource",
      "Resource": "arn:aws:fsx:*:*:volume/*/*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "bedrock:InvokeModel",
        "bedrock:Rerank"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "iam:PassRole"
      ],
      "Resource": [
        "arn:aws:iam::*:role/NetApp_AI_Bedrock_wlmai-*"
      ],
      "Effect": "Allow"
    },
    {
      "Action": [
        "ec2messages:GetMessages",
        "ec2messages:GetEndpoint",
        "ec2messages:AcknowledgeMessage",
        "ec2messages:DeleteMessage",
        "ec2messages:FailMessage",
        "ec2messages:SendReply"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "logs:DescribeLogGroups"
      ],
      "Resource": "*",
      "Effect": "Allow"
    },
    {
      "Action": [
        "logs:DescribeLogStreams",
        "logs:PutLogEvents",
        "logs:CreateLogStream",
        "logs:CreateLogGroup"
      ],
      "Resource": [
        "arn:aws:logs:*:*:log-group:/netapp/wlmai/*:log-stream:*",
        "arn:aws:logs:*:*:log-group:/netapp/wlmai/*"
      ],
      "Effect": "Allow"
    }
  ]
}
----
====
--
Groupe de sécurité:: Les règles sortantes sont ouvertes à tout le trafic, tandis que les règles entrantes sont complètement fermées.
Terminaux privés:: Si le VPC cible ne les possède pas déjà, la fabrique de workloads crée des terminaux privés pour l'instance EC2 du moteur GenAI afin qu'il puisse communiquer avec les services AWS suivants :
+
--
* Sol d'Amazon
+
** le socle
** durée de fonctionnement du système de roche
** bedrock-agent-runtime


* Amazon Elastic Container Registry (ECR)
+
** API
** docker


* AWS Systems Manager (SSM)
+
** ssm
** ec2messages
** ssmmessages


* Amazon FSX pour NetApp ONTAP
* Amazon CloudWatch


--

