---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documents GenAI
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez Workload Factory pour GenAI
      url: "/ai-workloads-overview.html"
    - title: Démarrage rapide
      url: "/quick-start.html"
    - title: Exigences GenAI
      url: "/requirements.html"
    - title: Identifiez les sources de données de votre base de connaissances
      url: "/identify-data-sources.html"
    - title: Déployez l'infrastructure de la base de connaissances
      url: "/deploy-infrastructure.html"
    - title: Utilisez l'exemple externe d'application chatbot
      url: "/example-chatbot-application.html"
  - title: Utilisez GenAI pour créer des bases de connaissances
    entries:
    - title: Créez une base de connaissances
      entries:
      - title: Créer une base de connaissances
        url: "/create-knowledgebase.html"
      - title: Testez une base de connaissances
        url: "/test-knowledgebase.html"
      - title: Activez l'authentification
        url: "/activate-authentication.html"
      - title: Publier une base de connaissances
        url: "/publish-knowledgebase.html"
      - title: Créez une application d'IA RAG
        url: "/create-application.html"
      - title: Que pouvez-vous faire ensuite
        url: "/whats-next.html"
    - title: Gérer les sources de données
      url: "/manage-data-source.html"
    - title: Gérer les bases de connaissances
      url: "/manage-knowledgebase.html"
  - title: Administrer GenAI
    entries:
    - title: Gérer l'infrastructure GenAI
      url: "/manage-infrastructure.html"
    - title: Composants du moteur NetApp GenAI
      url: "/genai-engine-instance.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support-registration.html"
    - title: Obtenez de l'aide
      url: "/get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP Workload Factory for AWS
  repo: workload-family
