---
settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documents GenAI
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Découvrez l'usine de workloads BlueXP  pour GenAI
    entries:
    - title: Découvrez l'usine de workloads BlueXP  pour GenAI
      url: "/general/ai-workloads-overview.html"
    - title: Composants du moteur NetApp GenAI
      url: "/general/genai-engine-instance.html"
  - title: Utilisez GenAI pour construire des bases de connaissances pour Amazon Bedrock
    entries:
    - title: Commencez
      entries:
      - title: Démarrage rapide
        url: "/knowledge-base/quick-start-knowledge-base.html"
      - title: Exigences de la base de connaissances
        url: "/knowledge-base/requirements-knowledge-base.html"
      - title: Identifier les sources de données à ajouter à une base de connaissances
        url: "/knowledge-base/identify-data-sources-knowledge-base.html"
      - title: Déployez l'infrastructure GenAI
        url: "/knowledge-base/deploy-infrastructure.html"
    - title: Créer une base de connaissances
      url: "/knowledge-base/create-knowledgebase.html"
    - title: Testez une base de connaissances
      url: "/knowledge-base/test-knowledgebase.html"
    - title: Activez l'authentification
      url: "/knowledge-base/activate-authentication.html"
    - title: Publier une base de connaissances
      url: "/knowledge-base/publish-knowledgebase.html"
    - title: Utilisez l'exemple externe d'application chatbot
      url: "/knowledge-base/example-chatbot-application.html"
    - title: Créez une application d'IA RAG
      url: "/knowledge-base/create-application.html"
    - title: Que pouvez-vous faire ensuite
      url: "/knowledge-base/whats-next.html"
  - title: Utilisez GenAI pour créer des connecteurs pour Amazon Q Business
    entries:
    - title: Commencez
      entries:
      - title: Démarrage rapide
        url: "/connector/quick-start-connector.html"
      - title: Exigences relatives au connecteur
        url: "/connector/requirements-connector.html"
      - title: Identifier les sources de données à ajouter à un connecteur
        url: "/connector/identify-data-sources-connector.html"
      - title: Déployez l'infrastructure GenAI
        url: "/connector/deploy-infrastructure.html"
    - title: Créez un connecteur NetApp ONTAP pour Amazon Q
      url: "/connector/define-connector.html"
  - title: Administration et contrôle
    entries:
    - title: Gérer l'infrastructure GenAI
      url: "/general/manage-infrastructure.html"
    - title: Gérer les bases de connaissances
      url: "/knowledge-base/manage-knowledgebase.html"
    - title: Gérer les connecteurs
      url: "/connector/manage-connector.html"
    - title: Gérer les sources de données
      url: "/general/manage-data-source.html"
    - title: Surveiller les opérations avec Tracker
      url: "/general/monitor-operations.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/support-registration.html"
    - title: Dépannage
      url: "/general/troubleshooting.html"
    - title: Obtenez de l'aide
      url: "/get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
