---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 'Découvrez les nouveautés de la fonctionnalité IA workloads de l"usine.' 
---
= Quoi de neuf
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la fonctionnalité Generative ai workloads d'usine.



== 01 décembre 2024



=== Cloner une base de connaissances à partir d'un instantané

L'usine de workloads BlueXP  pour GenAI prend désormais en charge le clonage d'une base de connaissances à partir d'un snapshot. Cela permet une récupération rapide des bases de connaissances et la création de nouvelles bases de connaissances avec les sources de données existantes, et aide à la récupération et au développement des données.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#clone-a-knowledge-base["Cloner une base de connaissances"]



=== Détection et réplication des clusters ONTAP sur site

Détectez et répliquez les données des clusters ONTAP sur site dans un système de fichiers FSX pour ONTAP afin de les utiliser pour enrichir les bases de connaissances d'IA. Tous les workflows de découverte et de réplication sur site sont possibles à partir du nouvel onglet *On-prlocale ONTAP* de l'inventaire du stockage.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Découvrez un cluster ONTAP sur site"]



== 3 novembre 2024



=== Masquez les informations à caractère personnel avec des limites de données

Le workload Generative ai introduit la fonctionnalité Data rambardes, optimisée par la classification BlueXP . La fonction Data guardrails identifie et masque les informations à caractère personnel (PII) pour vous aider à maintenir la conformité et à renforcer la sécurité de vos données d'entreprise sensibles.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["Créer une base de connaissances"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Découvrez la classification BlueXP"^]



== 29 septembre 2024



=== Prise en charge des snapshots et des restaurations pour les volumes de la base de connaissances

Vous pouvez désormais protéger les données de vos workloads d'IA générative en utilisant une copie instantanée d'une base de connaissances. Vous pouvez ainsi protéger vos données contre les pertes accidentelles ou tester les modifications apportées aux paramètres de la base de connaissances. Vous pouvez à tout moment restaurer la version précédente du volume de la base de connaissances.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["Prenez un instantané d'un volume de la base de connaissances"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["Restaurer un snapshot d'un volume de la base de connaissances"]



=== Mettre en pause les analyses planifiées

Vous pouvez maintenant interrompre les analyses de sources de données planifiées. Par défaut, les workloads d'IA génératifs analysent chaque source de données tous les jours afin d'ingérer de nouvelles données dans chaque base de connaissances. Si vous ne souhaitez pas que les dernières modifications soient ingérées (pendant le test ou lors de la restauration d'un instantané, par exemple), vous pouvez interrompre les analyses programmées et les reprendre à tout moment.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["Gérer les bases de connaissances"]



=== Les volumes de protection des données sont désormais pris en charge pour les bases de connaissances

Lors de la sélection d'un volume de la base de connaissances, vous pouvez désormais choisir un volume de protection des données faisant partie d'une relation de réplication NetApp SnapMirror. Cela vous permet de stocker des bases de connaissances sur des volumes déjà protégés par la réplication SnapMirror.

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["Identifiez les sources de données à intégrer dans votre base de connaissances"]



== 1er septembre 2024



=== Stratégies de chaquage supplémentaires

Les workloads d'IA génératifs prennent désormais en charge le traitement en plusieurs phrases et le processus de suppression basé sur les chevauchements pour les sources de données.



=== Volume dédié pour chaque base de connaissances

Les workloads d'IA génératifs créent désormais un volume Amazon FSX pour NetApp ONTAP dédié à chaque nouvelle base de connaissances, en activant des règles Snapshot individuelles pour chaque base de connaissances et en améliorant la protection contre les défaillances et les empoisonnements de données.



== 4 août 2024



=== Intégration des journaux Amazon CloudWatch

Les workloads d'IA génératifs sont désormais intégrés aux journaux Amazon CloudWatch, ce qui vous permet de surveiller les fichiers journaux des workloads d'IA génératifs.



=== Exemple d'application chatbot

L'exemple d'application GenAI de l'usine de workloads NetApp vous permet de tester l'authentification et l'extraction à partir de votre base de connaissances d'usine de workloads NetApp publiée en interagissant directement avec celle-ci dans une application de chatbot web.



== 7 juillet 2024



=== Version initiale de l'usine de charges de travail pour GenAI

La version initiale permet de développer une base de connaissances personnalisée en intégrant les données de votre entreprise. La base de connaissances est accessible par une application de chatbot pour vos utilisateurs. Cette fonctionnalité garantit des réponses précises et pertinentes aux questions spécifiques à l'entreprise, améliorant ainsi la satisfaction et la productivité de tous vos utilisateurs.
