---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 'Découvrez les nouveautés de la fonctionnalité IA workloads de l"usine.' 
---
= Nouveautés de l'usine de workloads BlueXP  pour l'IA Genai
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Découvrez les nouveautés de la fonctionnalité Generative ai workloads d'usine.



== 02 mars 2025



=== Améliorations du chatbot intégrées

Vous pouvez désormais copier des questions et des réponses directement dans le presse-papiers, ajuster la taille de la fenêtre de discussion et modifier son titre. De plus, les réponses de discussion peuvent maintenant inclure des tableaux, qui sont également copyables.

link:https://docs.netapp.com/us-en/workload-genai/test-knowledgebase.html["Testez une base de connaissances GenAI"]



=== Aide à la citation de réponse par chat

Les réponses à la discussion incluent maintenant des citations qui répertorient les fichiers et les segments de données utilisés pour générer la réponse.

link:https://docs.netapp.com/us-en/workload-genai/test-knowledgebase.html["Testez une base de connaissances GenAI"]



=== Prise en charge améliorée des types de fichiers

Cette version de GenAI fournit une prise en charge améliorée des fichiers :

* Les modèles de chat offrent une prise en charge CSV améliorée. Cela permet d'obtenir des réponses plus utiles lors de l'interrogation de données à partir de fichiers CSV.
* GenAI peut désormais ingérer des fichiers Apache parquet à partir de sources de données.
* GenAI prend désormais en charge l'ingestion de fichiers Microsoft Word DOCX contenant des images.


link:https://review.docs.netapp.com/us-en/workload-genai_mar-2-release/identify-data-sources.html#supported-data-source-file-formats["Formats de fichiers de source de données pris en charge"]



== 02 février 2025



=== Prise en charge des modèles de base Amazon Nova

GenAI prend désormais en charge les modèles de base Amazon Nova. Amazon Nova micro, Amazon Nova Lite et Amazon Nova Pro sont pris en charge.

link:https://docs.netapp.com/us-en/workload-genai/requirements.html["Exigences GenAI"]



=== Filtrage de type de fichier pour les sources de données

GenAI prend désormais en charge la sélection de types de fichiers spécifiques à inclure dans l'analyse de la source de données lorsque vous ajoutez une source de données.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Ajoutez des sources de données à la base de connaissances"]



=== Filtrage de date de modification de fichier pour les sources de données

GenAI prend désormais en charge le filtrage des fichiers à inclure dans l'analyse de la source de données par date de modification lorsque vous ajoutez une source de données. Vous pouvez choisir une plage de dates de modification pour les fichiers inclus.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Ajoutez des sources de données à la base de connaissances"]



=== Prise en charge des fichiers image et prise en charge améliorée des fichiers PDF

GenAI prend désormais en charge la numérisation de fichiers image et d'images dans des fichiers PDF (également appelés prise en charge de fichiers multimodaux). Si vous choisissez des fichiers image, le texte des images est numérisé dans la source de données et utilisé comme données. Cette fonction inclut des images dans des documents PDF ; si vous incluez des types de fichiers PDF, les images de chaque PDF sont numérisées pour du texte et ce texte est inclus dans les informations provenant de la source de données.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Ajoutez des sources de données à la base de connaissances"]



=== Recherche hybride et support de redirection

GenAI améliore désormais la pertinence des résultats de recherche grâce à la recherche hybride et à la réorganisation des résultats. La recherche hybride combine les recherches par mots clés avec la recherche vectorielle et sémantique. Les résultats standard de la recherche par mot-clé sont complétés par des correspondances étroites et la nuance linguistique, ce qui améliore la pertinence. GenAI réclasse les résultats de la recherche et ne renvoie que les résultats présentant la plus grande pertinence.

link:https://docs.netapp.com/us-en/workload-genai/ai-workloads-overview.html#benefits-of-using-genai-to-create-generative-ai-applications["Découvrez l'usine de workloads BlueXP  pour GenAI"]



== 05 janvier 2025



=== Nom de snapshot personnalisé

Vous pouvez maintenant fournir un nom d'instantané pour un instantané ad hoc.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#protect-a-knowledge-base-with-snapshots["Protégez une base de connaissances avec des instantanés"]



=== Nom d'instance de moteur d'IA personnalisé

Vous pouvez maintenant attribuer un nom personnalisé à l'instance du moteur d'IA pendant le déploiement.

link:https://docs.netapp.com/us-en/workload-genai/deploy-infrastructure.html["Déployez l'infrastructure GenAI"]



=== Reconstruction de l'infrastructure GenAI corrompue ou manquante

Si votre instance de moteur d'IA est corrompue ou supprimée, vous pouvez laisser la charge de travail se reconstruire en usine. Workload Factory rattache automatiquement vos bases de connaissances à l'infrastructure une fois la reconstruction terminée, afin qu'elles soient prêtes à l'emploi.

link:https://docs.netapp.com/us-en/workload-genai/troubleshooting.html["Dépannage"]



== 01 décembre 2024



=== Cloner une base de connaissances à partir d'un instantané

L'usine de workloads BlueXP  pour GenAI prend désormais en charge le clonage d'une base de connaissances à partir d'un snapshot. Cela permet une récupération rapide des bases de connaissances et la création de nouvelles bases de connaissances avec les sources de données existantes, et aide à la récupération et au développement des données.

link:https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#clone-a-knowledge-base["Cloner une base de connaissances"]



=== Détection et réplication des clusters ONTAP sur site

Détectez et répliquez les données des clusters ONTAP sur site dans un système de fichiers FSX pour ONTAP afin de les utiliser pour enrichir les bases de connaissances d'IA. Tous les workflows de découverte et de réplication sur site sont possibles à partir du nouvel onglet *On-prlocale ONTAP* de l'inventaire du stockage.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/use-onprem-data.html["Découvrez un cluster ONTAP sur site"]



== 3 novembre 2024



=== Masquez les informations à caractère personnel avec des limites de données

Le workload Generative ai introduit la fonctionnalité Data rambardes, optimisée par la classification BlueXP . La fonction Data guardrails identifie et masque les informations à caractère personnel (PII) pour vous aider à maintenir la conformité et à renforcer la sécurité de vos données d'entreprise sensibles.

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#create-and-configure-the-knowledge-base["Créer une base de connaissances"]

link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Découvrez la classification BlueXP"^]



== 29 septembre 2024



=== Prise en charge des snapshots et des restaurations pour les volumes de la base de connaissances

Vous pouvez désormais protéger les données de vos workloads d'IA générative en utilisant une copie instantanée d'une base de connaissances. Vous pouvez ainsi protéger vos données contre les pertes accidentelles ou tester les modifications apportées aux paramètres de la base de connaissances. Vous pouvez à tout moment restaurer la version précédente du volume de la base de connaissances.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html#take-a-snapshot-of-a-knowledge-base-volume["Prenez un instantané d'un volume de la base de connaissances"]

https://review.docs.netapp.com/us-en/workload-genai_29-sept-24-release/manage-knowledgebase.html#restore-a-snapshot-of-a-knowledge-base-volume["Restaurer un snapshot d'un volume de la base de connaissances"]



=== Mettre en pause les analyses planifiées

Vous pouvez maintenant interrompre les analyses de sources de données planifiées. Par défaut, les workloads d'IA génératifs analysent chaque source de données tous les jours afin d'ingérer de nouvelles données dans chaque base de connaissances. Si vous ne souhaitez pas que les dernières modifications soient ingérées (pendant le test ou lors de la restauration d'un instantané, par exemple), vous pouvez interrompre les analyses programmées et les reprendre à tout moment.

https://docs.netapp.com/us-en/workload-genai/manage-knowledgebase.html["Gérer les bases de connaissances"]



=== Les volumes de protection des données sont désormais pris en charge pour les bases de connaissances

Lors de la sélection d'un volume de la base de connaissances, vous pouvez désormais choisir un volume de protection des données faisant partie d'une relation de réplication NetApp SnapMirror. Cela vous permet de stocker des bases de connaissances sur des volumes déjà protégés par la réplication SnapMirror.

https://docs.netapp.com/us-en/workload-genai/identify-data-sources.html["Identifiez les sources de données à intégrer dans votre base de connaissances"]



== 1er septembre 2024



=== Stratégies de chaquage supplémentaires

Les workloads d'IA génératifs prennent désormais en charge le traitement en plusieurs phrases et le processus de suppression basé sur les chevauchements pour les sources de données.



=== Volume dédié pour chaque base de connaissances

Les workloads d'IA génératifs créent désormais un volume Amazon FSX pour NetApp ONTAP dédié à chaque nouvelle base de connaissances, en activant des règles Snapshot individuelles pour chaque base de connaissances et en améliorant la protection contre les défaillances et les empoisonnements de données.



== 4 août 2024



=== Intégration des journaux Amazon CloudWatch

Les workloads d'IA génératifs sont désormais intégrés aux journaux Amazon CloudWatch, ce qui vous permet de surveiller les fichiers journaux des workloads d'IA génératifs.



=== Exemple d'application chatbot

L'exemple d'application GenAI de l'usine de workloads NetApp vous permet de tester l'authentification et l'extraction à partir de votre base de connaissances d'usine de workloads NetApp publiée en interagissant directement avec celle-ci dans une application de chatbot web.



== 7 juillet 2024



=== Version initiale de l'usine de charges de travail pour GenAI

La version initiale permet de développer une base de connaissances personnalisée en intégrant les données de votre entreprise. La base de connaissances est accessible par une application de chatbot pour vos utilisateurs. Cette fonctionnalité garantit des réponses précises et pertinentes aux questions spécifiques à l'entreprise, améliorant ainsi la satisfaction et la productivité de tous vos utilisateurs.
