---
sidebar: sidebar 
permalink: knowledge-base/requirements-knowledge-base.html 
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements 
summary: 'Assurez-vous que l"usine de workloads et AWS sont correctement configurées avant de créer votre base de connaissances. Cela inclut notamment la mise à disposition de vos identifiants de connexion AWS, un système de fichiers FSX pour ONTAP déployé qui contient les sources de données que vous souhaitez intégrer dans votre base de connaissances, l"accès au service d"IA Amazon Bedrock, et bien plus encore.' 
---
= Exigences de la base de connaissances GenAI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Assurez-vous que l'usine de workloads et AWS sont correctement configurées avant de créer votre base de connaissances. Cela inclut notamment la mise à disposition de vos identifiants de connexion AWS, un système de fichiers FSX pour ONTAP déployé qui contient les sources de données que vous souhaitez intégrer dans votre base de connaissances, l'accès au service d'IA Amazon Bedrock, et bien plus encore.



== Exigences GenAI de base

GenAI présente des exigences générales que votre environnement doit satisfaire avant de commencer.

Connexion et compte d'usine de la charge de travail:: Vous devez vous https://docs.netapp.com/us-en/workload-setup-admin/sign-up-saas.html["configurez un compte avec une usine de charges de travail"^] connecter à l'aide de l'un des https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["expériences de la console"^].
Identifiants et autorisations AWS:: Vous devez ajouter les informations d'identification AWS à la fabrique de charges de travail avec des autorisations de lecture/écriture, ce qui signifie que vous utiliserez la fabrique de charges de travail en mode _lecture/écriture_ pour GenAI.
+
--
Les autorisations _Basic_ mode et _Read-Only_ mode ne sont pas prises en charge pour le moment.

Lors de la configuration de vos identifiants, le fait de sélectionner les autorisations comme indiqué ci-dessous vous permet de bénéficier d'un accès complet pour gérer les systèmes de fichiers FSX pour ONTAP, ainsi que pour déployer et gérer l'instance EC2 GenAI et d'autres ressources AWS nécessaires à votre base de connaissances et à votre chatbot.

https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Découvrez comment ajouter des identifiants AWS à l'usine de workloads"^]

--




== Exigences de la base de connaissances GenAI

Si vous prévoyez de travailler avec des bases de connaissances, assurez-vous que votre environnement répond aux exigences suivantes.

Sol d'Amazon:: Amazon Bedrock vous permet d'utiliser des modèles de base et offre les fonctionnalités nécessaires pour créer des applications d'IA générative.
+
--
Avant de vous lancer avec l'usine de workloads BlueXP  pour GenAI, vous devez configurer Amazon Bedrock. Votre déploiement GenAI doit se trouver dans une région AWS sur laquelle Amazon Bedrock est activé.

* https://docs.aws.amazon.com/bedrock/latest/userguide/setting-up.html["Documentation AWS : configurez Amazon Bedrock"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-supported.html["Documentation AWS : régions et modèles pris en charge pour les bases de connaissances pour Amazon Bedrock"^]


GenAI classe par défaut les résultats de recherche pour en améliorer la pertinence. Pour obtenir les meilleurs résultats, assurez-vous que votre configuration de modèle de base Amazon Bedrock inclut l'accès à un modèle de classement, tel que Cohere Rerank ou Amazon Rerank, si disponible dans votre région.

--
Modèle d'intégration:: Vous devez activer le modèle d'intégration que vous prévoyez d'utiliser avant de créer votre base de connaissances. Les modèles d'intégration suivants sont pris en charge :
+
--
* Codes Titan G1 - texte
* Texte d'intégration Titan v2
* Embedding multimodal G1 Titan
* Intégrer l'anglais
* Intégrer multilingue
+
https://aws.amazon.com/bedrock/titan/["En savoir plus sur Amazon Titan"^]



--
Modèle de chat:: Vous devez activer le modèle de chat de base que vous prévoyez d'utiliser avant de créer votre base de connaissances. Étant donné que la prise en charge des modèles varie selon les régions AWS, reportez-vous à la section https://docs.aws.amazon.com/bedrock/latest/userguide/models-regions.html["La documentation AWS"^] pour vérifier les modèles que vous pouvez utiliser dans les régions où vous prévoyez de déployer votre base de connaissances.
+
--
GenAI prend en charge divers modèles de Anthropic, Amazon, Mistral ai, Meta, Jamba, et Cohere.

En savoir plus sur l'utilisation de ces modèles dans Amazon Bedrock :

* https://aws.amazon.com/bedrock/claude/["Claude d'anthropic dans le sol d'Amazon"^]
* https://docs.aws.amazon.com/nova/latest/userguide/getting-started-console.html["Prise en main d'Amazon Nova dans la console Amazon Bedrock"^]
* https://aws.amazon.com/bedrock/mistral/["Modèles d'IA Mistral"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modèles texte Amazon Titan"^]
* https://aws.amazon.com/bedrock/llama/["Modèles META Llama"^]
* https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-jamba.html["Modèles Jamba"^]
* https://aws.amazon.com/bedrock/cohere/["Modèles Cohere Command"^]


--
FSX pour le système de fichiers ONTAP:: Vous avez besoin d'au moins un système de fichiers FSX pour ONTAP :
+
--
* Un système de fichiers sera utilisé (ou créé, s'il n'existe pas) par le moteur NetApp GenAI pour stocker la base de données vectorielle utilisée par la base de connaissances.
+
Ce système de fichiers FSX pour ONTAP doit utiliser des volumes FlexVol. Les volumes FlexGroup ne sont pas pris en charge.

* Un ou plusieurs systèmes de fichiers contiendront les sources de données que vous intégrerez dans votre base de connaissances.
+
Un système de fichiers FSX pour ONTAP peut être utilisé pour ces deux raisons ou vous pouvez utiliser plusieurs systèmes de fichiers FSX pour ONTAP.

* Vous devez connaître la région AWS, le VPC et le sous-réseau où réside le système de fichiers AWS FSX pour ONTAP. Le système de fichiers doit se trouver dans une région AWS sur laquelle Amazon Bedrock est activé.
* Vous devrez tenir compte des paires clé/valeur que vous souhaitez appliquer aux ressources AWS faisant partie de ce déploiement (facultatif).
* Vous devrez connaître les informations relatives aux paires de clés qui vous permettront de vous connecter en toute sécurité à l'instance du moteur NetApp ai.


https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Découvrez comment déployer et gérer les systèmes de fichiers FSX pour ONTAP"^]

--

